global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: linker-metrics

rule_files: 
-  /etc/prometheus/prometheus.rules
-  /etc/prometheus/generated/*.rules

scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  scrape_timeout: 4s 

  static_configs:
    # These endpoints are scraped via HTTP.
    - targets: ['master.mesos:10005']
